apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "<chart name>.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "<chart name>.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "<chart name>.fullname" . }}
    spec:
      serviceAccountName: gke-service-account
      containers:
      - name: <chart name>
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.service.Port }}
        env:
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "{{ .Values.db.port }}"
        - name: DB_NAME
          value: "{{ .Values.db.name }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        volumeMounts:
        - name: config-volume
          mountPath: /app/
          subPath: .env
   
      volumes:
      - name: config-volume
        configMap:
          name: config

